/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  LeaClassLookupType: "CODE" | "NAME"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token?: string | null; // String
  }
  Document: { // root type
    description: string; // String!
    name: string; // String!
    posted: string; // String!
    viewed: boolean; // Boolean!
  }
  LeaClass: { // root type
    average?: number | null; // Float
    code: string; // String!
    distributedAssignments?: number | null; // Int
    distributedDocuments?: number | null; // Int
    grade?: string | null; // String
    median?: number | null; // Float
    schedule?: string[] | null; // [String!]
    teacher: string; // String!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string | null; // String
  }
  Document: { // field return type
    description: string; // String!
    name: string; // String!
    posted: string; // String!
    viewed: boolean; // Boolean!
  }
  LeaClass: { // field return type
    average: number | null; // Float
    code: string; // String!
    distributedAssignments: number | null; // Int
    distributedDocuments: number | null; // Int
    grade: string | null; // String
    median: number | null; // Float
    schedule: string[] | null; // [String!]
    teacher: string; // String!
    title: string; // String!
  }
  Mutation: { // field return type
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
  }
  Query: { // field return type
    LeaClass: NexusGenRootTypes['LeaClass'][] | null; // [LeaClass!]
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
  }
  Document: { // field return type name
    description: 'String'
    name: 'String'
    posted: 'String'
    viewed: 'Boolean'
  }
  LeaClass: { // field return type name
    average: 'Float'
    code: 'String'
    distributedAssignments: 'Int'
    distributedDocuments: 'Int'
    grade: 'String'
    median: 'Float'
    schedule: 'String'
    teacher: 'String'
    title: 'String'
  }
  Mutation: { // field return type name
    login: 'AuthPayload'
  }
  Query: { // field return type name
    LeaClass: 'LeaClass'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    login: { // args
      id: string; // String!
      password: string; // String!
    }
  }
  Query: {
    LeaClass: { // args
      lookUpType: NexusGenEnums['LeaClassLookupType']; // LeaClassLookupType!
      search: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}